services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: to_do_db
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 10s
            retries: 10

    app:
        build:
            context: .
        container_name: laravel_app
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=mysql
        networks:
            - app_network

volumes:
    mysql_data:
        driver: local

networks:
    app_network:
        driver: bridge
